name: Run Weather Script

on:
  schedule:
    - cron: '0 10 * * *'  # รันทุกวันเวลา 10:00 AM
    - cron: '0 12 * * *'  # รันทุกวันเวลา 12:00 PM
    - cron: '0 17 * * *'  # รันทุกวันเวลา 5:00 PM
  workflow_dispatch:  # อนุญาตให้รัน workflow ด้วยตนเอง

jobs:
  run-weather-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install requests gitpython

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Run weather script
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          source .venv/bin/activate
          python weather.py